import os
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, Optional


class MarkdownStorage:
    def __init__(self, base_path: str, organize_by_date: bool = True):
        self.base_path = Path(base_path)
        self.organize_by_date = organize_by_date
        self.base_path.mkdir(parents=True, exist_ok=True)
    
    def _generate_filename(self, video_id: str, title: str = "") -> str:
        safe_title = self._sanitize_filename(title)
        if safe_title:
            return f"{video_id}_{safe_title}.md"
        return f"{video_id}.md"
    
    def _sanitize_filename(self, filename: str) -> str:
        if not filename:
            return ""
        
        invalid_chars = '<>:"/\\|?*'
        for char in invalid_chars:
            filename = filename.replace(char, '_')
        
        filename = filename.strip()
        
        if len(filename) > 50:
            filename = filename[:50].strip()
        
        return filename
    
    def _get_storage_path(self, video_id: str, title: str = "") -> Path:
        if self.organize_by_date:
            date_folder = datetime.now().strftime("%Y-%m")
            storage_path = self.base_path / date_folder
        else:
            storage_path = self.base_path
        
        storage_path.mkdir(parents=True, exist_ok=True)
        filename = self._generate_filename(video_id, title)
        return storage_path / filename
    
    def save_transcript(self, transcript_data: Dict[str, Any], summary: str = None) -> str:
        video_id = transcript_data['video_id']
        title = transcript_data.get('title', '')
        file_path = self._get_storage_path(video_id, title)
        
        markdown_content = self._format_as_markdown(transcript_data, summary)
        
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(markdown_content)
        
        return str(file_path)
    
    def _format_as_markdown(self, transcript_data: Dict[str, Any], summary: str = None) -> str:
        video_id = transcript_data['video_id']
        language = transcript_data.get('language', 'unknown')
        is_generated = transcript_data.get('is_generated', False)
        title = transcript_data.get('title', f"YouTube Video {video_id}")
        duration = transcript_data.get('duration', 'unknown')
        
        youtube_url = f"https://www.youtube.com/watch?v={video_id}"
        
        content = f"""# {title}

## Video Information
- **Video ID**: {video_id}
- **URL**: [{youtube_url}]({youtube_url})
- **Language**: {language}
- **Auto-generated**: {is_generated}
- **Duration**: {duration}
- **Processed**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

"""
        
        if summary:
            content += f"""## Summary
{summary}

"""
        
        content += f"""## Transcript
{transcript_data.get('cleaned_text', transcript_data.get('formatted_text', ''))}

---
*Generated by dAstIll - YouTube Transcript Loader*
"""
        
        return content
    
    def load_transcript(self, video_id: str) -> Optional[str]:
        for path in self.base_path.rglob(f"{video_id}_*.md"):
            with open(path, 'r', encoding='utf-8') as f:
                return f.read()
        
        for path in self.base_path.rglob(f"{video_id}.md"):
            with open(path, 'r', encoding='utf-8') as f:
                return f.read()
        
        return None
    
    def file_exists(self, video_id: str) -> bool:
        return any(self.base_path.rglob(f"{video_id}_*.md")) or any(self.base_path.rglob(f"{video_id}.md"))