import os
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, Optional


class MarkdownStorage:
    def __init__(self, base_path: str, organize_by_date: bool = True, 
                 downloaded_path: str = None, processed_path: str = None):
        self.base_path = Path(base_path)
        self.downloaded_path = Path(downloaded_path) if downloaded_path else self.base_path
        self.processed_path = Path(processed_path) if processed_path else self.base_path
        self.organize_by_date = organize_by_date
        
        # Create all paths if they don't exist
        self.base_path.mkdir(parents=True, exist_ok=True)
        self.downloaded_path.mkdir(parents=True, exist_ok=True)
        self.processed_path.mkdir(parents=True, exist_ok=True)
    
    def _generate_filename(self, video_id: str, title: str = "") -> str:
        safe_title = self._sanitize_filename(title)
        if safe_title:
            return f"{video_id}_{safe_title}.md"
        return f"{video_id}.md"
    
    def _sanitize_filename(self, filename: str) -> str:
        if not filename:
            return ""
        
        invalid_chars = '<>:"/\\|?*'
        for char in invalid_chars:
            filename = filename.replace(char, '_')
        
        filename = filename.strip()
        
        if len(filename) > 50:
            filename = filename[:50].strip()
        
        return filename
    
    def _get_storage_path(self, video_id: str, title: str = "", status: str = "downloaded", channel: str = "unknown") -> Path:
        # Choose base path based on status
        if status == "downloaded":
            base = self.downloaded_path
        elif status == "processed":
            base = self.processed_path
        else:
            base = self.base_path
        
        # For processed files, organize by channel; for downloaded, keep them in status folder
        if status == "processed":
            storage_path = base / channel
        else:
            if self.organize_by_date:
                date_folder = datetime.now().strftime("%Y-%m")
                storage_path = base / date_folder
            else:
                storage_path = base
        
        storage_path.mkdir(parents=True, exist_ok=True)
        filename = self._generate_filename(video_id, title)
        return storage_path / filename
    
    def save_transcript(self, transcript_data: Dict[str, Any], summary: str = None, status: str = "downloaded", channel: str = "unknown") -> str:
        video_id = transcript_data['video_id']
        title = transcript_data.get('title', '')
        
        try:
            file_path = self._get_storage_path(video_id, title, status, channel)
            markdown_content = self._format_as_markdown(transcript_data, summary)
            
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(markdown_content)
                f.flush()  # Ensure data is written to disk
                os.fsync(f.fileno())
            
            return str(file_path)
            
        except PermissionError as e:
            raise IOError(f"Permission denied writing to {file_path}: {str(e)}")
        except OSError as e:
            raise IOError(f"Failed to write transcript file {file_path}: {str(e)}")
        except Exception as e:
            raise IOError(f"Unexpected error saving transcript: {str(e)}")
    
    def _format_as_markdown(self, transcript_data: Dict[str, Any], summary: str = None) -> str:
        video_id = transcript_data['video_id']
        language = transcript_data.get('language', 'unknown')
        is_generated = transcript_data.get('is_generated', False)
        title = transcript_data.get('title', f"YouTube Video {video_id}")
        duration = transcript_data.get('duration', 'unknown')
        
        youtube_url = f"https://www.youtube.com/watch?v={video_id}"
        
        content = f"""# {title}

## Video Information
- **Video ID**: {video_id}
- **URL**: [{youtube_url}]({youtube_url})
- **Language**: {language}
- **Auto-generated**: {is_generated}
- **Duration**: {duration}
- **Processed**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

"""
        
        if summary:
            content += f"""## Summary
{summary}

"""
        
        content += f"""## Transcript
{transcript_data.get('cleaned_text', transcript_data.get('formatted_text', ''))}

---
*Generated by dAstIll - YouTube Transcript Loader*
"""
        
        return content
    
    def load_transcript(self, video_id: str) -> Optional[str]:
        patterns = [f"{video_id}_*.md", f"{video_id}.md"]
        
        for pattern in patterns:
            try:
                for path in self.base_path.rglob(pattern):
                    try:
                        with open(path, 'r', encoding='utf-8') as f:
                            return f.read()
                    except PermissionError as e:
                        raise IOError(f"Permission denied reading {path}: {str(e)}")
                    except UnicodeDecodeError as e:
                        raise IOError(f"Failed to decode file {path}: {str(e)}")
                    except OSError as e:
                        raise IOError(f"Failed to read transcript file {path}: {str(e)}")
            except Exception as e:
                # Log the error but continue searching
                continue
        
        return None
    
    def file_exists(self, video_id: str) -> bool:
        return any(self.base_path.rglob(f"{video_id}_*.md")) or any(self.base_path.rglob(f"{video_id}.md"))
    
    def move_file(self, video_id: str, from_status: str, to_status: str, title: str = "", channel: str = "unknown") -> Optional[str]:
        """Move a transcript file from one status path to another."""
        # Find the existing file
        from_base = self._get_base_path_for_status(from_status)
        patterns = [f"{video_id}_*.md", f"{video_id}.md"]
        
        source_file = None
        for pattern in patterns:
            matches = list(from_base.rglob(pattern))
            if matches:
                source_file = matches[0]
                break
        
        if not source_file:
            return None
        
        # Generate destination path
        dest_path = self._get_storage_path(video_id, title or source_file.stem.split('_', 1)[-1], to_status, channel)
        
        try:
            # Read the content
            with open(source_file, 'r', encoding='utf-8') as f:
                content = f.read()
            
            # Write to new location
            with open(dest_path, 'w', encoding='utf-8') as f:
                f.write(content)
                f.flush()
                os.fsync(f.fileno())
            
            # Remove the old file
            source_file.unlink()
            
            # Clean up empty date folders
            parent = source_file.parent
            if parent != from_base and not any(parent.iterdir()):
                parent.rmdir()
            
            return str(dest_path)
            
        except Exception as e:
            raise IOError(f"Failed to move file from {source_file} to {dest_path}: {str(e)}")
    
    def _get_base_path_for_status(self, status: str) -> Path:
        """Get the base path for a given status."""
        if status == "downloaded":
            return self.downloaded_path
        elif status == "processed":
            return self.processed_path
        else:
            return self.base_path