// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Video } from "./Video";

export type AddVideoResponse = { video: Video, target_channel_id: string, already_exists: boolean, };
