// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiStatus } from "./AiStatus";

export type AiHealthPayload = { available: boolean, status: AiStatus, };
