// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncDepthPayload } from "./SyncDepthPayload";
import type { Video } from "./Video";

export type ChannelSnapshotPayload = {
  channel_id: string;
  sync_depth: SyncDepthPayload;
  /**
   * Total videos stored for this channel when cheaply available.
   */
  channel_video_count: number | null;
  has_more: boolean;
  next_offset: number | null;
  videos: Array<Video>;
};
