// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Video } from "./Video";

export type ChannelVideoPagePayload = {
  videos: Array<Video>;
  has_more: boolean;
  next_offset: number | null;
};
