// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncDepthPayload } from "./SyncDepthPayload";
import type { Video } from "./Video";

export type ChannelSnapshotPayload = { channel_id: string, sync_depth: SyncDepthPayload, videos: Array<Video>, };
