// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Channel = {
  id: string;
  handle: string | null;
  name: string;
  thumbnail_url: string | null;
  added_at: string;
  earliest_sync_date: string | null;
  earliest_sync_date_user_set: boolean;
};
