// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatTitleStatus } from "./ChatTitleStatus";

export type ChatConversationSummary = {
  id: string;
  title: string | null;
  title_status: ChatTitleStatus;
  created_at: string;
  updated_at: string;
};
