// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatTurnBudgetSnapshot } from "./ChatTurnBudgetSnapshot";
import type { ChatTurnRetrievalTrace } from "./ChatTurnRetrievalTrace";
import type { ChatTurnToolTrace } from "./ChatTurnToolTrace";

export type ChatTurnTrace = { strategy: string, plan_intent?: string, plan_label?: string, tool_calls: Array<ChatTurnToolTrace>, retrieval?: ChatTurnRetrievalTrace, budget: ChatTurnBudgetSnapshot, };
