// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchSourceKind } from "./SearchSourceKind";

export type ChatSource = {
  video_id: string;
  channel_id: string;
  channel_name: string;
  video_title: string;
  source_kind: SearchSourceKind;
  section_title: string | null;
  snippet: string;
  score: number;
  chunk_id: string;
  retrieval_pass?: number;
};
