// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatTurnBudgetSnapshot = { max_model_calls: number, model_calls: number, max_tool_calls: number, tool_calls: number, max_retrieval_passes: number, retrieval_passes: number, exhausted: boolean, exhaustion_reason?: string, };
