// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatTurnRetrievalTrace = { pass_count: number, query_count: number, selected_source_count: number, unique_video_count: number, deep_research: boolean, };
