// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessageStatus } from "./ChatMessageStatus";
import type { ChatRole } from "./ChatRole";
import type { ChatSource } from "./ChatSource";

export type ChatMessage = {
  id: string;
  role: ChatRole;
  content: string;
  sources: Array<ChatSource>;
  status: ChatMessageStatus;
  created_at: string;
};
