// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";
import type { ChatTitleStatus } from "./ChatTitleStatus";

export type ChatConversation = { id: string, title: string | null, title_status: ChatTitleStatus, created_at: string, updated_at: string, messages: Array<ChatMessage>, };
