// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatModelOption } from "./ChatModelOption";

export type ChatClientConfig = {
  /**
   * Default cloud model id when the client omits `model` on send.
   */
  default_model: string;
  /**
   * Curated Ollama cloud models the client may offer in a selector.
   */
  models: Array<ChatModelOption>;
};
