// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CleanTranscriptResponse = { content: string, preserved_text: boolean, attempts_used: number, max_attempts: number, timed_out: boolean, };
