// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentAvailability } from "./ContentAvailability";
import type { ContentPartKind } from "./ContentPartKind";
import type { TranscriptRenderMode } from "./TranscriptRenderMode";

export type ContentPart = {
  id: string;
  item_id: string;
  kind: ContentPartKind;
  availability: ContentAvailability;
  render_mode?: TranscriptRenderMode;
  text_length?: number;
};
