// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentPartKind } from "./ContentPartKind";
import type { ContentStatus } from "./ContentStatus";
import type { ProviderKind } from "./ProviderKind";

export type ContentPart = { id: string, source_id: string, item_id: string, provider: ProviderKind, part_kind: ContentPartKind, status: ContentStatus, text_available: boolean, };
