// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentProvider } from "./ContentProvider";
import type { LibrarySectionKind } from "./LibrarySectionKind";
import type { ProviderMetadataEntry } from "./ProviderMetadataEntry";
import type { SourceArchetype } from "./SourceArchetype";
import type { SourceBackingKind } from "./SourceBackingKind";
import type { SubscriptionContainerKind } from "./SubscriptionContainerKind";

export type ContentSource = {
  id: string;
  provider: ContentProvider;
  section: LibrarySectionKind;
  archetype: SourceArchetype;
  container_kind: SubscriptionContainerKind;
  backing: SourceBackingKind;
  container_id?: string;
  title: string;
  subtitle?: string;
  thumbnail_url?: string;
  added_at: string;
  item_count?: number;
  unread_count?: number;
  provider_metadata: Array<ProviderMetadataEntry>;
};
