// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentItemKind } from "./ContentItemKind";
import type { ProviderIdentity } from "./ProviderIdentity";
import type { ProviderKind } from "./ProviderKind";

export type ContentItem = {
  id: string;
  source_id: string;
  provider: ProviderKind;
  item_kind: ContentItemKind;
  title: string;
  thumbnail_url?: string;
  published_at?: string;
  external_ids: Array<ProviderIdentity>;
};
