// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentSourceKind =
  | "you_tube_channel"
  | "podcast_series"
  | "publication_series"
  | "saved_search"
  | "authenticated_publisher_source"
  | "website"
  | "standalone_tracked_source";
