// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentAvailability } from "./ContentAvailability";
import type { ContentItemKind } from "./ContentItemKind";
import type { ContentPartKind } from "./ContentPartKind";
import type { ContentProvider } from "./ContentProvider";
import type { MediaAssetKind } from "./MediaAssetKind";

export type ContentItem = {
  id: string;
  source_id: string;
  provider: ContentProvider;
  item_kind: ContentItemKind;
  title: string;
  thumbnail_url?: string;
  published_at: string;
  acknowledged: boolean;
  availability: ContentAvailability;
  available_parts: Array<ContentPartKind>;
  available_media_assets: Array<MediaAssetKind>;
};
