// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentAvailability =
  | "metadata_only"
  | "partial"
  | "full"
  | "entitlement_required"
  | "session_expired"
  | "extraction_failed";
