// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HighlightSource } from "./HighlightSource";

export type CreateHighlightRequest = { source: HighlightSource, text: string, prefix_context: string, suffix_context: string, };
