// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatConversation } from "./ChatConversation";

/**
 * Anonymous-only chat turn: full conversation state is carried by the client; nothing is written to the store.
 */
export type EphemeralChatMessageRequest = {
  conversation: ChatConversation;
  content: string;
  deep_research: boolean;
  model?: string;
};
