// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentItemKind } from "./ContentItemKind";
import type { Highlight } from "./Highlight";
import type { ProviderKind } from "./ProviderKind";

export type HighlightVideoGroup = { source_id: string, video_id: string, item_id: string, provider: ProviderKind, item_kind: ContentItemKind, title: string, thumbnail_url: string | null, published_at: string, highlights: Array<Highlight>, };
