// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HighlightVideoGroup } from "./HighlightVideoGroup";

export type HighlightChannelGroup = {
  channel_id: string;
  channel_name: string;
  channel_thumbnail_url: string | null;
  videos: Array<HighlightVideoGroup>;
};
