// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Highlight } from "./Highlight";

export type HighlightVideoGroup = {
  video_id: string;
  title: string;
  thumbnail_url: string | null;
  published_at: string;
  highlights: Array<Highlight>;
};
