// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentSourceKind } from "./ContentSourceKind";
import type { HighlightVideoGroup } from "./HighlightVideoGroup";
import type { ProviderKind } from "./ProviderKind";

export type HighlightChannelGroup = {
  source_id: string;
  channel_id: string;
  provider: ProviderKind;
  source_kind: ContentSourceKind;
  channel_name: string;
  channel_thumbnail_url: string | null;
  videos: Array<HighlightVideoGroup>;
};
