// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentItem } from "./ContentItem";
import type { ContentSource } from "./ContentSource";
import type { LibrarySectionSummary } from "./LibrarySectionSummary";
import type { WebsiteFolder } from "./WebsiteFolder";

export type LibraryBootstrapPayload = { sections: Array<LibrarySectionSummary>, sources: Array<ContentSource>, selected_source_id: string | null, selected_source?: ContentSource, selected_items: Array<ContentItem>, website_folders: Array<WebsiteFolder>, };
