// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibrarySectionKind } from "./LibrarySectionKind";
import type { SourceBackingKind } from "./SourceBackingKind";
import type { SubscriptionContainerKind } from "./SubscriptionContainerKind";

export type LibrarySectionSummary = {
  kind: LibrarySectionKind;
  title: string;
  source_count: number;
  item_count: number;
  container_kinds: Array<SubscriptionContainerKind>;
  backing_kinds: Array<SourceBackingKind>;
};
