// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaAssetKind } from "./MediaAssetKind";
import type { ProviderKind } from "./ProviderKind";

export type MediaAsset = { id: string, source_id: string, item_id: string, provider: ProviderKind, asset_kind: MediaAssetKind, title: string, url?: string, mime_type?: string, };
