// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentAvailability } from "./ContentAvailability";
import type { MediaAssetKind } from "./MediaAssetKind";

export type MediaAsset = {
  id: string;
  item_id: string;
  kind: MediaAssetKind;
  availability: ContentAvailability;
  mime_type?: string;
};
