// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenAlexSavedSearchQuery } from "./OpenAlexSavedSearchQuery";

export type OpenAlexPlanResponse = {
  query: OpenAlexSavedSearchQuery;
  notes: Array<string>;
  display_label: string;
};
