// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderKind = "you_tube" | "new_york_times" | "podcast_rss" | "open_alex" | "arxiv" | "semantic_scholar" | "website" | "manual";
