// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentItemKind } from "./ContentItemKind";
import type { ContentSourceKind } from "./ContentSourceKind";
import type { ProviderKind } from "./ProviderKind";
import type { SearchMatchPayload } from "./SearchMatchPayload";

export type SearchVideoResultPayload = {
  source_id: string;
  video_id: string;
  item_id: string;
  provider: ProviderKind;
  source_kind: ContentSourceKind;
  item_kind: ContentItemKind;
  channel_id: string;
  channel_name: string;
  video_title: string;
  published_at: string;
  matches: Array<SearchMatchPayload>;
};
