// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchSourceKind } from "./SearchSourceKind";

export type SearchMatchPayload = {
  source: SearchSourceKind;
  section_title: string | null;
  snippet: string;
  score: number;
  /**
   * Start position in the video for deep-link playback. Only present for
   * transcripts extracted via yt-dlp (the summarize CLI path has no timestamps).
   */
  start_sec?: number;
};
