// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchSourceKind } from "./SearchSourceKind";

export type SearchMatchPayload = {
  source: SearchSourceKind;
  section_title: string | null;
  snippet: string;
  score: number;
};
