// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchStatusPayload = {
  available: boolean;
  model: string;
  dimensions: number;
  pending: number;
  indexing: number;
  ready: number;
  failed: number;
  total_sources: number;
  total_chunk_count: number;
  embedded_chunk_count: number;
  vector_index_ready: boolean;
  retrieval_mode: string;
};
