// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SendChatMessageRequest = {
  content: string;
  /**
   * When true, retrieval uses the maximum excerpt budget and multi-query passes so the model can synthesize across much more of the library.
   */
  deep_research: boolean;
  /**
   * Ollama cloud model id from [`ChatClientConfig::models`]. When omitted, the server default cloud model is used.
   */
  model?: string;
};
