// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SourceArchetype =
  | "feed_backed_series"
  | "query_backed_source"
  | "authenticated_publisher"
  | "manual_website"
  | "video_channel";
