// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SourceBackingKind =
  | "feed_backed"
  | "query_backed"
  | "manually_curated"
  | "authenticated_session";
