// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SummaryEvaluationJob = { video_id: string, video_title: string, transcript_text: string, summary_content: string, };
