// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Summary = {
  video_id: string;
  content: string;
  model_used: string | null;
  quality_score: number | null;
  quality_note: string | null;
  quality_model_used: string | null;
};
