// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A time-stamped caption segment from yt-dlp json3 output.
 * Only present on transcripts extracted via the yt-dlp fallback path.
 */
export type TimedSegment = {
  /**
   * Start position in the video, in seconds.
   */
  start_sec: number;
  text: string;
};
