// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptRenderMode } from "./TranscriptRenderMode";

export type Transcript = { video_id: string, raw_text: string | null, formatted_markdown: string | null, render_mode: TranscriptRenderMode, };
