// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserPreferences = {
  /**
   * Ordered list of channel IDs for the "custom" sort mode.
   */
  channel_order: Array<string>;
  /**
   * Which sort mode is active: "custom", "alpha", or "newest".
   */
  channel_sort_mode: string;
};
