// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VideoInfo = {
  video_id: string;
  watch_url: string;
  title: string;
  description: string | null;
  thumbnail_url: string | null;
  channel_name: string | null;
  channel_id: string | null;
  published_at: string | null;
  duration_iso8601: string | null;
  duration_seconds: bigint | null;
  view_count: bigint | null;
};
