// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentStatus } from "./ContentStatus";

export type Video = { id: string, channel_id: string, title: string, thumbnail_url: string | null, published_at: string, is_short: boolean, transcript_status: ContentStatus, summary_status: ContentStatus, acknowledged: boolean, retry_count: number, quality_score?: number, };
