// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VocabularyReplacement = {
  from: string;
  to: string;
  added_at: string;
};
