// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebsiteFolder = {
  id: string;
  name: string;
  position: number;
  created_at: string;
  updated_at: string;
  website_count: number;
};
