// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiStatus } from "./AiStatus";
import type { Channel } from "./Channel";
import type { ChannelSnapshotPayload } from "./ChannelSnapshotPayload";
import type { ContentSource } from "./ContentSource";
import type { LibraryBootstrapPayload } from "./LibraryBootstrapPayload";
import type { SearchStatusPayload } from "./SearchStatusPayload";
import type { SubscriptionContainer } from "./SubscriptionContainer";

export type WorkspaceBootstrapPayload = { ai_available: boolean, ai_status: AiStatus, analytics_enabled: boolean, containers: Array<SubscriptionContainer>, sources: Array<ContentSource>, channels: Array<Channel>, selected_source_id: string | null, selected_channel_id: string | null, selected_item_id?: string, snapshot: ChannelSnapshotPayload | null, library: LibraryBootstrapPayload, search_status: SearchStatusPayload, };
