// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiStatus } from "./AiStatus";
import type { Channel } from "./Channel";
import type { ChannelSnapshotPayload } from "./ChannelSnapshotPayload";
import type { SearchStatusPayload } from "./SearchStatusPayload";

export type WorkspaceBootstrapPayload = {
  ai_available: boolean;
  ai_status: AiStatus;
  channels: Array<Channel>;
  selected_channel_id: string | null;
  snapshot: ChannelSnapshotPayload | null;
  search_status: SearchStatusPayload;
};
