// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchMatchPayload } from "./SearchMatchPayload";

export type SearchVideoResultPayload = { video_id: string, channel_id: string, channel_name: string, video_title: string, published_at: string, matches: Array<SearchMatchPayload>, };
