// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SummaryEvaluationResult = { quality_score: number, quality_note: string | null, quality_model_used: string | null, };
