// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncDepthPayload = { earliest_sync_date: string | null, earliest_sync_date_user_set: boolean, derived_earliest_ready_date: string | null, };
