// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptRenderMode } from "./TranscriptRenderMode";

export type UpdateContentRequest = { content: string, render_mode: TranscriptRenderMode | null, };
