from datetime import datetime
from pathlib import Path
from typing import Any


class TranscriptFormatter:
    def __init__(self, base_path: str):
        self.base_path = Path(base_path)

    def _sanitize_channel_name(self, channel: str) -> str:
        """Sanitize channel name to prevent path traversal and invalid chars."""
        if not channel or channel.strip() == "":
            return "unknown"

        # Remove path traversal attempts
        channel = channel.replace("..", "").replace("/", "").replace("\\", "")

        # Remove invalid filesystem characters
        invalid_chars = '<>:"|?*'
        for char in invalid_chars:
            channel = channel.replace(char, "")

        # Limit length and strip whitespace
        channel = channel.strip()[:100]  # Max 100 chars

        # If empty after sanitization, use unknown
        return channel if channel else "unknown"

    def format_transcript_content(self, transcript_data: dict[str, Any], summary: str = None) -> str:
        """Format transcript data as markdown content."""
        video_id = transcript_data['video_id']
        language = transcript_data.get('language', 'unknown')
        is_generated = transcript_data.get('is_generated', False)
        title = transcript_data.get('title', f"YouTube Video {video_id}")
        duration = transcript_data.get('duration', 'unknown')

        youtube_url = f"https://www.youtube.com/watch?v={video_id}"

        content = f"""# {title}

## Video Information
- **Video ID**: {video_id}
- **URL**: [{youtube_url}]({youtube_url})
- **Language**: {language}
- **Auto-generated**: {is_generated}
- **Duration**: {duration}
- **Downloaded**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

"""

        if summary:
            content += f"""## Summary
{summary}

"""

        content += f"""## Transcript
{transcript_data.get('cleaned_text', transcript_data.get('formatted_text', ''))}

---
*Generated by dAstIll - YouTube Transcript Loader*
"""

        return content

    def _sanitize_filename(self, filename: str) -> str:
        """Sanitize filename for safe file system usage."""
        if not filename:
            return ""

        invalid_chars = '<>:"/\\|?*'
        for char in invalid_chars:
            filename = filename.replace(char, '_')

        filename = filename.strip()

        if len(filename) > 50:
            filename = filename[:50].strip()

        return filename

    def _generate_filename(self, video_id: str, title: str = "", channel: str = "unknown") -> str:
        """Generate a safe filename for the transcript."""
        safe_title = self._sanitize_filename(title)
        safe_channel = self._sanitize_channel_name(channel)

        if safe_channel != "unknown":
            if safe_title:
                return f"{video_id}_{safe_channel}_{safe_title}.md"
            return f"{video_id}_{safe_channel}.md"
        else:
            if safe_title:
                return f"{video_id}_{safe_title}.md"
            return f"{video_id}.md"
