from datetime import datetime
from pathlib import Path
from typing import Any


class TranscriptFormatter:
    def __init__(self, base_path: str):
        self.base_path = Path(base_path)

    def _sanitize_channel_name(self, channel: str | None) -> str:
        """Sanitize channel name to prevent path traversal and invalid chars."""
        if not channel or not isinstance(channel, str) or channel.strip() == "":
            return "unknown"

        # Use whitelist approach - only allow safe characters
        import re

        # Allow only alphanumeric, spaces, hyphens, underscores, and basic punctuation
        # Explicitly exclude dots to prevent path traversal attacks
        safe_chars = re.sub(r"[^a-zA-Z0-9\s\-_()[\]{}!]", "", channel)

        # Normalize whitespace and remove multiple spaces
        safe_chars = " ".join(safe_chars.split())

        # Limit length and strip whitespace
        safe_chars = safe_chars.strip()[:100]  # Max 100 chars

        # If empty after sanitization, use unknown
        return safe_chars if safe_chars else "unknown"

    def format_transcript_content(
        self, transcript_data: dict[str, Any], summary: str = None
    ) -> str:
        """Format transcript data as markdown content."""
        video_id = transcript_data["video_id"]
        language = transcript_data.get("language", "unknown")
        is_generated = transcript_data.get("is_generated", False)
        title = transcript_data.get("title", f"YouTube Video {video_id}")
        duration = transcript_data.get("duration", "unknown")

        youtube_url = f"https://www.youtube.com/watch?v={video_id}"

        content = f"""# {title}

## Video Information
- **Video ID**: {video_id}
- **URL**: [{youtube_url}]({youtube_url})
- **Language**: {language}
- **Auto-generated**: {is_generated}
- **Duration**: {duration}
- **Downloaded**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

"""

        if summary:
            content += f"""## Summary
{summary}

"""

        content += f"""## Transcript
{transcript_data.get("cleaned_text", transcript_data.get("formatted_text", ""))}

---
*Generated by dAstIll - YouTube Transcript Loader*
"""

        return content

    def _sanitize_filename(self, filename: str | None) -> str:
        """Sanitize filename for safe file system usage."""
        if not filename or not isinstance(filename, str):
            return ""

        # Use whitelist approach for filenames - be more restrictive than channel names
        import re

        # Allow only alphanumeric, spaces, hyphens, underscores, and periods
        # No path separators or special characters that could cause issues
        safe_chars = re.sub(r"[^a-zA-Z0-9\s\-_.]", "", filename)

        # Normalize whitespace and remove multiple spaces
        safe_chars = " ".join(safe_chars.split())

        # Remove leading/trailing periods to prevent hidden files
        safe_chars = safe_chars.strip(". ")

        # Limit length
        if len(safe_chars) > 50:
            safe_chars = safe_chars[:50].strip()

        return safe_chars

    def _generate_filename(
        self, video_id: str, title: str = "", channel: str = "unknown"
    ) -> str:
        """Generate a safe filename for the transcript."""
        safe_title = self._sanitize_filename(title)
        safe_channel = self._sanitize_channel_name(channel)

        if safe_channel != "unknown":
            if safe_title:
                return f"{video_id}_{safe_channel}_{safe_title}.md"
            return f"{video_id}_{safe_channel}.md"
        else:
            if safe_title:
                return f"{video_id}_{safe_title}.md"
            return f"{video_id}.md"
